config/routes.rb
Rails3MongoidDevise::Application.routes.draw do
  resources :images

root :to => "home#index"

  devise_for :users
  resources :users, :only => :show
          
 

end

app/models/image.rb
require 'mongoid_paperclip'
class Image 
  include Mongoid::Document 
  include Mongoid::Paperclip

  has_mongoid_attached_file :image
  attr_accessible :image
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Adding names to model
  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gridfs_controller.rb
require 'mongo'
        
        class GridfsController < ActionController::Metal
          def serve
            gridfs_path = env["PATH_INFO"].gsub("/images/", "")
            begin
              gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
              self.response_body = gridfs_file.read
              self.content_type = gridfs_file.content_type
            rescue
              self.status = :not_found
              self.content_type = 'text/plain'
              self.response_body = ''
            end
          end
        end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  @users = User.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @image }
#    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
def show
  @user = User.find(params[:id])
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p>Is this really how easy it is? - <b>Hamish</b></p>

<h3>Home</h3>

<p>All the content is inside here - you must register or sign on to proceed </p>

app/views/images/_form.html.erb
<%= form_for :image, @image, :url => user_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :image %>
<% end %> 

app/views/images/edit.html.erb
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<div class="hero-unit">
<h1>An example gallery</h1>
<p>We shall see how the layout looks now!"</p>
</div>

<div class="row">
<div class="span10">
<div class="alert">
 <a class="close" data-dismiss="alert">×</a>
 <strong>ALERT!</strong> - there are errors that can be shown and CLOSED!
</div>
<div class="alert alert-info">
 <a class="close" data-dismiss="alert">×</a>
 <strong>IMPORTANT!</strong> - then there are information boxes in blue but they can still be CLOSED!
</div>

<ul class="thumbnails">
  <li class="span3">
    <a href="#" class="thumbnail">
     <img src="http://placehold.it/260x180" alt="">
    </a>
  </li>

  <li class="span3">
    <a href="#" class="thumbnail">
     <img src="http://placehold.it/260x180" alt="">
    </a>
  </li>

  <li class="span3">
    <a href="#" class="thumbnail">
      <img src="http://placehold.it/260x180" alt="">
    </a>
  </li>
</ul>


<ul class="thumbnails">
  <li class="span3">
    <a href="#" class="thumbnail">
      <img src="http://placehold.it/260x180" alt="">
    </a>
  </li>

  <li class="span3">
    <a href="#" class="thumbnail">
      <img src="http://placehold.it/260x180" alt="">
    </a>
  </li>

  <li class="span3">
    <a href="#" class="thumbnail">
     <img src="http://placehold.it/260x180" alt="">
    </a>
  </li>
</ul>

</div>

</div>
<%= link_to 'New', new_image_path, :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<h1>Image</h1>

<p id="notice"><%= notice %></p>
        <%= image_tag @image.image.url(:thumb) %>
        
        <%= link_to 'Edit', edit_image_path(@image) %> |
        <%= link_to 'Back', images_path %>


<div class="form-actions">
  <%= link_to 'Back', images_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_image_path(@image), :class => 'btn' %>
  <%= link_to 'Delete', image_path(@image), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3MongoidDevise</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
<div class="container">
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Home</a>
        <div class="nav-collapse">
          <ul class="nav">
	    <li><%= render 'shared/navigation' %>
            <li><%= link_to "Placeholder" %></li>
            <li><%= link_to "Placeholder" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div> 

<!-- <ul class="hmenu">
    < % = render 'shared/navigation' %>
  </ul> -->
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>

    <div class="row">
	<p>
          <br />	<br />
	</p>
      <div class="span10"><%= yield %></div>
      <div class="span2">
        <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
    <div class="row">
       <div class="span3">
	<p>Col 1 footer
       </div>
       <div class="span3">
	<p> Col 2 footer</p>
       </div>
       <div class="span3">
        <p>Col 3 footer</p>
       </div>
       </div>
    </div>
  </div>

</body>
</html>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
<li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
</li>
<% else %>
<li>
  <%= link_to('Login', new_user_session_path)  %>  
</li>
<% end %>
<% if user_signed_in? %>
<li>
  <%= link_to('Edit account', edit_user_registration_path) %>
</li>
<% else %>
<li>
  <%= link_to('Sign up', new_user_registration_path)  %>
</li>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> User</legend>

    <div class="control-group">
      <%= f.label :_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :_type, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :_id, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :encrypted_password, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :encrypted_password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :reset_password_token, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :reset_password_token, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :reset_password_sent_at, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :reset_password_sent_at, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :remember_created_at, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :remember_created_at, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sign_in_count, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :sign_in_count, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :current_sign_in_at, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_sign_in_at, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :last_sign_in_at, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_sign_in_at, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :current_sign_in_ip, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :last_sign_in_ip, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th> type</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user._type, user_path(user) %></td>
        <td><%= user.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_user_path, :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h1>User</h1>

<p>
  <b> type</b><br>
  <%= @user._type %>
</p>

<p>
  <b></b><br>
  <%= @user._id %>
</p>

<p>
  <b>Email</b><br>
  <%= @user.email %>
</p>

<p>
  <b>Encrypted password</b><br>
  <%= @user.encrypted_password %>
</p>

<p>
  <b>Reset password token</b><br>
  <%= @user.reset_password_token %>
</p>

<p>
  <b>Reset password sent at</b><br>
  <%= @user.reset_password_sent_at %>
</p>

<p>
  <b>Remember created at</b><br>
  <%= @user.remember_created_at %>
</p>

<p>
  <b>Sign in count</b><br>
  <%= @user.sign_in_count %>
</p>

<p>
  <b>Current sign in at</b><br>
  <%= @user.current_sign_in_at %>
</p>

<p>
  <b>Last sign in at</b><br>
  <%= @user.last_sign_in_at %>
</p>

<p>
  <b>Current sign in ip</b><br>
  <%= @user.current_sign_in_ip %>
</p>

<p>
  <b>Last sign in ip</b><br>
  <%= @user.last_sign_in_ip %>
</p>

<p>
  <b>Name</b><br>
  <%= @user.name %>
</p>